#Screen variables
MAX_WIDTH = 1920
MAX_HEIGHT = 1080

#Board variables
BORDER_RADIUS = 20
P_BORDER_RADIUS = 50
PADDING = 10

BOARD_X = MAX_WIDTH / 6
BOARD_Y = MAX_HEIGHT / 3
BOARD_POS = (BOARD_X, BOARD_Y)
BOARD_WIDTH = MAX_WIDTH / 1.5
BOARD_HEIGHT = MAX_HEIGHT / 3
BOARD_SIZE = (BOARD_WIDTH, BOARD_HEIGHT)

POCKET_WIDTH = 140
POCKET_SIZE = (POCKET_WIDTH, POCKET_WIDTH)

HOME_SIZE = (POCKET_WIDTH, 340)

#Color values
BG_C = "#e0edb7"
BOARD_C = "#8a7b4a"
BOARD_OL_C = "#78663d"
POCKET_C = "#7a6c3e"
POCKET_OL_C = "#a3935f"
STONE_C = "#4ce0aa"
